keys:
  - &admin_soriphoono C2B9FC8254BAFAE7DB22909CE805BC8E17D7B0A8
  - &system_wsl age1q0we70gk6uj4y92hdnwj06vcfm74h0h8dd7cyl07sdv5d93h5qsqlkm0wh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_soriphoono
        age:
          - *system_wsl
