keys:
  - &admin_soriphoono age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn

  - &system_testbench age1lqd89ed3x2j58kq4xckle5dwvdyt8kqkwwmaf0dw5e35sy2q9ptq8qzyhm
  - &system_zephyrus
creation_rules:
  - path_regex: homes/.*/soriphoono/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
        - *system_testbench

  - path_regex: systems/.*/minimal/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono

  - path_regex: systems/.*/testbench/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
        - *system_testbench

  - path_regex: systems/.*/zephyrus/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
        - *system_zephyrus
