keys:
  - &admin_recovery age177swcgdm7684cxtkghjkm4c8mhfmx8yqj0vlhd0ath0t52v06vtsl5qdr2
  - &admin_soriphoono age1e5jg7tt5czmwrty4w8unh6ajqsh9npn0dplxcfmjw8c3h6r39g9q2dggfu

  - &server_workstation age1y99wglmp3pnpmg9rrzutda3wg68wsnpmslmlx4eymkfhc9zusd4se4t6ge
  - &server_zephyrus age17n8s2ekm9txtamhclwwlkv33tm2ppvy0agsqxplgfdp09uj05v3qdk5nk4
  - &server_testbench age1fx8z5th0qy6qtm458t07z6xhlkp6mnnx9fl7zd22ctcks532yuusxum9ym
creation_rules:
  - path_regex: homes/.*/soriphoono/secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_recovery
          - *admin_soriphoono
  - path_regex: systems/.*/.*/.*.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_recovery
          - *admin_soriphoono
          - *server_workstation
          - *server_zephyrus
          - *server_testbench
