keys:
  - &admin_soriphoono age1e5jg7tt5czmwrty4w8unh6ajqsh9npn0dplxcfmjw8c3h6r39g9q2dggfu
creation_rules:
  - path_regex: homes/.*/.*/secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
