keys:
  - &admin_recovery age177swcgdm7684cxtkghjkm4c8mhfmx8yqj0vlhd0ath0t52v06vtsl5qdr2
  - &admin_soriphoono age1e5jg7tt5czmwrty4w8unh6ajqsh9npn0dplxcfmjw8c3h6r39g9q2dggfu

  - &server_zephyrus age15r8n4c77m6jdcar93fq6fjlhjzygx0cupj9y2t3wux2xnv5xj4zql3a2hl
creation_rules:
  - path_regex: homes/.*/soriphoono/secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_recovery
        - *admin_soriphoono
  - path_regex: secrets/global.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_recovery
        - *server_zephyrus

