keys:
  - &admin_soriphoono age1e5jg7tt5czmwrty4w8unh6ajqsh9npn0dplxcfmjw8c3h6r39g9q2dggfu

  - &server_wsl_desktop age1ayntxnj78awwr53j4a3322mpfkrvacdhu4yg6uumej8px2vuascsnzlypt
  - &server_wsl_zephyrus age15nx5unrgh5839jha6k6dy5pa6ldkdft5g83dx5n347pxdax8nqsqq8a77u
  - &server_zephyrus age1pf95vtfx9ftqekrrn7ec5lpsrxpnqw2pqlppuz2zhqcnzts3cvtqazv648
creation_rules:
  - path_regex: homes/.*/.*/secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
  - path_regex: secrets/global.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_soriphoono
        - *server_wsl_desktop
        - *server_wsl_zephyrus
        - *server_zephyrus
