keys:
  - &admin_soriphoono age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn

  - &system_testbench age1gsusf43rnpef0lv8qxj5nzx0vuale209msehdxjy8584naym3eksd7ghnw
creation_rules:
  - path_regex: homes/.*/soriphoono/secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
  - path_regex: systems/.*/.*/.*.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
          - *system_testbench
