#!/usr/bin/env bash

packages=(
  "stow"
  "git"
)

sudo apt install "${packages[@]}"

# Install all relevant features
for entry in $(find ./ -type d);
do
    if [[ -f ./$entry/module.sh ]];
    then
        source ./$entry/module.sh

        module-$(basename $entry)
    fi
done

# Write global configuration using gnu stow


# Copy dotfiles for current user

