#!/bin/bash

# Setup pacman.conf and paru.conf
# Create pacman.conf.bak or restore it if it exists
if [[ -f /etc/pacman.conf.bak ]]; then
    sudo mv /etc/pacman.conf.bak /etc/pacman.conf
fi
sudo cp /etc/pacman.conf /etc/pacman.conf.bak
echo "Created pacman.conf backup file"

# Setup parallel downloads and colored output
sudo sed -i 's/#Color/Color/g' /etc/pacman.conf
sudo sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 5/g' /etc/pacman.conf
echo "Setup parallel downloads and colored output for pacman"

sh ~/.config/yadm/core/repos.sh

# Update system
sudo pacman -Syu --noconfirm >/dev/null

# Install paru
sudo pacman -S --noconfirm --needed paru >/dev/null
echo "Installed paru aur helper"

# Create paru.conf.bak or restore it if it exists
if [[ -f /etc/paru.conf.bak ]]; then
    sudo mv /etc/paru.conf.bak /etc/paru.conf
fi
sudo cp /etc/paru.conf /etc/paru.conf.bak
echo "Created paru.conf backup file"

# Setup bottom up reading of available packages for paru.conf
sudo sed -i 's/#BottomUp/BottomUp/g' /etc/paru.conf
echo "Setup bottom up reading of available packages for paru.conf"

# Configure mirrors using reflector
paru -S --noconfirm --needed reflector rsync
sudo mv /etc/xdg/reflector/reflector.conf /etc/xdg/reflector/reflector.conf.bak
echo -e "--save /etc/pacman.d/mirrorlist\n--sort rate\n--protocol https\n--latest 15" | sudo tee /etc/xdg/reflector/reflector.conf >/dev/null
sudo systemctl start reflector.service >/dev/null
sudo systemctl enable --now reflector.timer >/dev/null
echo "Enabled reflector.timer"

# Install submodules
yadm submodule init >/dev/null
yadm submodule update >/dev/null
echo "Installed submodules"

paru -c --noconfirm >/dev/null

# Install cli packages
sh ~/.config/yadm/drivers/bootstrap --multilib
sh ~/.config/yadm/cli/bootstrap
sh ~/.config/yadm/desktop.sh
sh ~/.config/yadm/personal/bootstrap --multilib

# Copy configuration files
sudo cp -r ~/.config/yadm/conf/* /

# Reboot system
read -p "Press any key to reboot..." -n 1 -r
reboot
