#!/bin/bash

# Path:         ~/.config/yadm/personal/bootstrap
# Description:  Bootstrap script for personal packages
# Author:       Sori Phoono <soriphoono@gmail.com>

MULTILIB=false
for arg in "$@"; do
    case $arg in
    -m | --multilib)
        MULTILIB=true
        ;;
    esac
done

read -p "Install general packages? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/general_tools.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Install developer environment? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/developer_environment.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Install office tools? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/office.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Install gaming tools? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/gaming.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Install recording/streaming tools? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/recording_tools.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Install editing tools? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh ~/.config/yadm/personal/editing_tools.sh $(if $MULTILIB; then echo "--multilib"; fi)
fi

read -p "Do you want to copy monitor configs? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Copying monitor configs..."
    sudo cp -r ~/.config/yadm/personal/conf/* /
fi

paru -c --noconfirm >/dev/null
