#!/bin/bash

# Path:         ~/.config/yadm/personal/bootstrap
# Description:  Bootstrap script for personal packages
# Author:       Sori Phoono <soriphoono@gmail.com>

MULTILIB=false
for arg in "$@"; do
    case $arg in
    -m | --multilib)
        MULTILIB=true
        ;;
    esac
done

feature_sets=()

i=1
echo "Feature sets for personal packages: "
source_blacklist=(
    "~/.config/yadm/personal/bootstrap.sh"
    "~/.config/yadm/personal/conf/"
)
for source_file in $(find ~/.config/yadm/personal -name "*.sh"); do
    skip=false
    for blacklist in "${source_blacklist[@]}"; do
        if [ $source_file = $blacklist ]; then
            skip=true
            break
        fi
    done
    if [ $skip = false ]; then
        echo "$i) $(basename $source_file | sed 's/.sh//')"
        feature_sets+=("$source_file")
        i=$((i + 1))
    fi
done
read -p "Select feature set: " feature_set

feature_set_len=${#feature_sets[@]}
feature_set_len=$((feature_set_len + 1))
for feature_set in $feature_set; do
    if [ $feature_set -gt 0 ] && [ $feature_set -lt $feature_set_len ]; then
        sh ${feature_sets[$((feature_set - 1))]} $($MULTILIB && echo "--multilib")
    else
        echo "Invalid feature set index: $feature_set"
    fi
done

read -p "Do you want to copy monitor configs? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Copying monitor configs..."
    sudo cp -r ~/.config/yadm/personal/conf/* /
fi
