[General]
DisplayServer=wayland
CompositorCommand=/usr/bin/Hyprland # TODO: add custom configuration to render sddm compositor

[Theme]
# Current theme name
Current=sugar-candy

# Cursor theme used in the greeter
CursorTheme=Catppuccin-Mocha-Teal-Cursors