#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

monitor=,preferred,auto,auto

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    repeat_rate = 30
    repeat_delay = 200
    sensitivity = 0.4
    accel_profile = "flat"
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 20
    gaps_out = 20
    border_size = 3
    col.active_border = rgba(1e1e2eff)
    col.inactive_border = rgba(181825)

    layout = dwindle

    cursor_inactive_timeout = 60

    resize_on_border = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 8
    
    blur {
        enabled = true
        size = 5.8
        passes = 2
        new_optimizations = true
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(313244ff)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = overshot,0.10,0.9,0.1,1

    animation = windows, 1, 3, default, popin
    animation = windowsIn, 1, 3, default, popin 80%
    animation = windowsOut, 1, 3, default, popin 80%
    animation = windowsMove, 1, 3, default, slide
    animation = workspaces, 1, 5, overshot, slidevert
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

misc {
    disable_hyprland_logo = true
    animate_manual_resizes = true
    disable_autoreload = true
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = false
}

source = ~/.config/hypr/dispatchers.conf
source = ~/.config/hypr/autostart.conf