#!/bin/bash

kernels=(
    "linux",
    "linux-lts",
    "linux-hardened",
    "linux-zen",
)

kernel_supporting=(
    "linux-firmware",
    "linux-firmware-qlogic",
    "linux-firmware-bnx2x",
    "linux-firmware-liquidio",
    "linux-firmware-mellanox",
    "linux-firmware-nfp",
)

packages=(
    "base-devel",
    "dosfstools",
    "exfatprogs",
    "xdg-user-dirs",
    "pacman-contrib",
    "nano",
    "neovim",
    "tmux",
    "zsh",
    "oh-my-zsh-git",
    "starship",
    "neofetch",
    "usbutils",
    "curl",
    "eza",
    "bat",
    "diff-so-fancy",
    "dua-cli",
    "duf",
    "tre-command",
    "scc",
    "jq",
    "btop",
)

# Install kernel for linux
while true; do
    i=1

    echo "Available kernels:"
    for kernel in "${kernels[@]}"; do
        echo "    $i: $kernel"
        i=$((i + 1))
    done

    read -p "Select kernel: " kernel

    if [[ $kernel -ge 0 && $kernel -lt ${#kernels[@]} ]]; then
        paru -S --noconfirm --needed "${kernels[$i - 1]} ${kernels[$i - 1]}-headers" >>/dev/null 2>&1
        paru -S --noconfirm --needed "${kernel_supporting[@]}" >>/dev/null 2>&1
        break
    fi
done

# Install packages from list
paru -S --noconfirm --needed "${packages[@]}" >>/dev/null 2>&1

source ./networking.sh
