---
- name: Install amd base drivers
  become: true
  ansible.builtin.package:
    name:
      - mesa
      - xf86-video-amdgpu
      - vulkan-radeon

      - lib32-mesa
      - lib32-vulkan-radeon

      - clinfo

      - ocl-icd
      - opencl-rusticl-mesa

      - lib32-ocl-icd
      - lib32-opencl-rusticl-mesa
    state: present

- name: Prompt for hardware accleration support
  ansible.builtin.pause:
    prompt: "Do you want to install hardware acceleration support (mesa)? (y/n)"
  register: amd_integrated

- name: Detect hardware acceleration configuration file
  ansible.builtin.stat:
    path: /etc/profile.d/99-hardware-acceleration.sh
  register: hardware_acceleration_check
  when: amd_integrated == "y"

- name: Configure environment variables for hardware acceleration on amdgpu
  become: true
  ansible.builtin.template:
    src: templates/drivers/etc/profile.d/99-hardware-acceleration.sh.j2
    dest: /etc/profile.d/99-hardware-acceleration.sh
    owner: root
    group: root
    mode: '0644'
  vars:
    libva_driver_name: radeonsi
    vdpau_driver_name: radeonsi
  when:
    - amd_integrated == "y"
    - not hardware_acceleration_check.stat.exists

- name: Prompt for dedicated gpu support
  ansible.builtin.pause:
    prompt: "Do you want to install dedicated GPU support (rocm)? (y/n)"
  register: amd_dedicated

- name: Install dedicated GPU support (rocm)
  become: true
  ansible.builtin.package:
    name:
      - rocm-hip-runtime
      - rocm-opencl-runtime
      - hiprt
    state: present
  when: amd_dedicated == "y"
