---
- name: Install NVIDIA drivers
  become: true
  ansible.builtin.package:
    name:
      - nvidia-open-dkms

      - nvidia-utils
      - ocl-icd
      - opencl-nvidia

      - lib32-nvidia-utils
      - lib32-ocl-icd
      - lib32-opencl-nvidia

      - nvidia-settings
      - nvidia-prime
      - clinfo
      - cuda
    state: present

- name: Auto rebuild initramfs on NVIDIA driver update
  become: true
  ansible.builtin.copy:
    src: files/drivers/etc/pacman.d/hooks/nvidia.hook
    dest: /etc/pacman.d/hooks/nvidia.hook
    owner: root
    group: root
    mode: '0644'

- name: Copy NVIDIA power management configuration
  become: true
  ansible.builtin.copy:
    src: files/drivers/etc/modprobe.d/nvidia-pm.conf
    dest: /etc/modprobe.d/nvidia-pm.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy NVIDIA power management configuration (continued)
  become: true
  ansible.builtin.copy:
    src: files/drivers/etc/udev/rules.d/80-nvidia-pm.rules
    dest: /etc/udev/rules.d/80-nvidia-pm.rules
    owner: root
    group: root
    mode: '0644'
