# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A minimal left prompt
format = """$directory $character"""

# move the rest of the prompt to the right
right_format = """$all"""

command_timeout = 1000

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[](bold red)" # The 'error_symbol' segment is being set to '➜' with the color 'bold red'

[hostname]
ssh_symbol = " "

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = "…"
style = "bold white"

[memory_usage]
symbol = "󰍛 "

[directory]
read_only = " 󰌾"
truncation_length = 8
truncation_symbol = '…/'

[c]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
