---
- name: Install chaotic-AUR
  ansible.builtin.import_tasks: chaotic-aur.yml

- name: Install tools
  become: true
  ansible.builtin.package:
    name:
      - paru
      - pacman-contrib
      - reflector
      - plymouth
      - plymouth-theme-dna-git
      - libpwquality
      - firewalld
      - easyeffects
      - calf
      - lsp-plugins-lv2
      - zam-plugins-lv2
      - stow
      - ttf-sourcecodepro-nerd
      - otf-aurulent-nerd
      - bibata-cursor-translucent
      - papirus-icon-theme
      - fish
      - starship
      - btop
      - eza
      - fastfetch
      - nvtop
      - nodejs
      - npm
      - rustup
      - ripgrep
      - direnv
      - less
      - git-delta
      - firefox
      - profile-sync-daemon
      - discord
      - signal-desktop
      - element-desktop
      - bitwarden
      - onlyoffice-bin
      - thunderbird
      - neovim
      - visual-studio-code-bin
      - obsidian
      - gimp
      - inkscape
      - krita
      - tenacity
      - blender
      - tailscale
    state: present
  notify:
    - Enable paccache.timer
    - Enable reflector.timer
    - Enable firewalld.service
    - Enable bluetooth.service
    - Enable psd.service (user)

- name: Configure bootloader
  become: true
  ansible.builtin.lineinfile:
    path: "/boot/loader/entries/linux-zen.conf"
    line: "options plymouth.use-simpledrm splash quiet"
    insertafter: "^options"  # Adjust this to place the line appropriately
    state: present

- name: Deploy dotfiles
  ansible.builtin.command: stow -R .
  args:
    chdir: ~/.dotfiles
    creates:
      - ~/.config/environment.d
      - ~/.config/fastfetch
      - ~/.config/fish
      - ~/.config/nvim
      - ~/.config/starship.toml

- name: Set default shell
  become: true
  ansible.builtin.command: chsh -s /usr/bin/fish soriphoono

- name: Install rust sdk
  ansible.builtin.command: rustup default stable
