---
- name: Copy files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/pam.d/passwd
    - etc/pam.d/system-login
    - etc/plymouth/plymouthd.conf
    - etc/ssh/sshd_config.d/20-deny_root.conf
    - etc/ssh/sshd_config.d/20-force_publickey_auth.conf
    - etc/sudoers.d/10-wheel
    - etc/mkinitcpio.conf
    - etc/pacman.conf
    - etc/paru.conf

- name: Install chaotic-AUR
  ansible.builtin.import_tasks: chaotic-aur.yml

- name: Install tools
  become: true
  ansible.builtin.package:
    name:
      - paru
      - pacman-contrib
      - reflector

      - plymouth
      - plymouth-theme-dna-git

      - libpwquality
      - firewalld

      - easyeffects
      - calf
      - lsp-plugins-lv2
      - zam-plugins-lv2

      - stow

      - ttf-sourcecodepro-nerd
      - otf-aurulent-nerd
      - bibata-cursor-translucent
      - papirus-icon-theme

      - fish
      - starship
      - fastfetch
      - direnv
      - eza
      - ripgrep
      - git-delta
      - less
      - btop
      - nvtop

      - tailscale

      - firefox
      - profile-sync-daemon

      - discord
      - signal-desktop
      - element-desktop

      - onlyoffice-bin
      - thunderbird

      - rustup
      - nodejs
      - npm
      - neovim

      - obsidian
      - bitwarden
      - visual-studio-code-bin

      - krita
      - gimp
      - inkscape

      - tenacity

      - blender
    state: present
  notify:
    - Enable paccache.timer
    - Enable reflector.timer
    - Enable firewalld.service
    - Enable bluetooth.service
    - Enable psd.service (user)

- name: Rebuild initramfs
  become: true
  ansible.builtin.command: mkinitcpio -P

- name: Configure bootloader
  become: true
  ansible.builtin.lineinfile:
    path: "/boot/loader/entries/linux-zen.conf"
    line: "options plymouth.use-simpledrm splash quiet"
    insertafter: "^options"  # Adjust this to place the line appropriately
    state: present

- name: Deploy dotfiles
  ansible.builtin.command: stow -R .
  args:
    chdir: ~/.dotfiles
    creates:
      - ~/.config/environment.d
      - ~/.config/fastfetch
      - ~/.config/fish
      - ~/.config/nvim
      - ~/.config/starship.toml

- name: Set default shell
  become: true
  ansible.builtin.command: chsh -s /usr/bin/fish soriphoono

- name: Install rust sdk
  ansible.builtin.command: rustup default stable
