#!/bin/bash

# Path:         ~/.config/yadm/drivers/bootstrap

# Description:  Install gpu drivers, cpu microcode, and other hardware related packages

gpus_installed=$(lspci | grep -e "3D" -e "VGA" >>/dev/null 2>&1)
gpu_count=$(grep "" -c <<<"$gpus_installed")
nvidia=false
for gpu in "$gpus_installed"; do
    case "$gpu" in
    "*NVIDIA*")
        nvidia=true
        ;;
    esac
done

installed=()

if [ $gpu_count -lt 3 ]; then
    if [ $gpu_count == 2 ]; then
        read -p "Two GPUs detected, please confirm that one is an integrated gpu before installation. [y/n]" -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            cpu_type=$(lscpu | grep "Vendor ID" | cut -d ":" -f 2 | sed -e 's/^[[:space:]]*//')

            case "$cpu_type" in
            "GenuineIntel")
                sh "$HOME/.config/yadm/drivers/intel.sh" --integrated

                installed+=("intel")
                ;;
            "AuthenticAMD")
                sh "$HOME/.config/yadm/drivers/amd.sh" --integrated

                installed+=("amd")
                ;;
            esac
        else
            echo "Please install drivers manually"

            exit 0
        fi
    fi

    if $nvidia; then
        sh "$HOME/.config/yadm/drivers/nvidia.sh"
    else
        for gpu in "$gpus_installed"; do
            case "$gpu" in
            "*AMD*")
                if [[ ! " ${installed[@]} " =~ "amd" ]]; then
                    sh "$HOME/.config/yadm/drivers/amd.sh" --discrete

                    installed+=("amd")
                fi
                ;;

            "*Intel*")
                if [[ ! " ${installed[@]} " =~ "intel" ]]; then
                    sh "$HOME/.config/yadm/drivers/intel.sh" --discrete

                    installed+=("intel")
                fi
                ;;
            esac
        done
    fi
else
    echo "Unusual number of GPUs detected, please install drivers manually"

    exit 0
fi
