galaxy_info:
  author: Sori Phoono <soriphoono@protonmail.com>
  description: An Ansible role to install AMD GPU drivers on Linux.

  license: GPL-2.0-or-later

  min_ansible_version: '2.1'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: [
    "amd",
    "gpu",
    "graphics",
    "driver",
    "linux"
  ]

dependencies:
  - role: drivers
