galaxy_info:
  author: Sori Phoono <soriphoono@protonmail.com>
  description: An Ansible role to install Intel GPU drivers on Linux.

  license: GPL-2.0-or-later

  min_ansible_version: '2.1'

  galaxy_tags: [
    intel,
    amd,
    gpu,
    drivers,
    linux,
    microcode,
    firmware,
  ]
