exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --all &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = swayidle -w timeout 300 'swaylock' before-sleep 'swaylock' &
exec-once = swayidle -w timeout 450 'pidof java || systemctl suspend' & # dont sleep if playing minecraft, else nvidia will fuck up

exec = if [[ $(pgrep ags) ]]; then pkill ags; fi && ags
exec-once = swww init && ~/.config/hypr/scripts/wallpaper.sh

exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha-Standard-Teal-Dark'

exec-once = easyeffects --gapplication-service
exec-once = discord --start-minimized
