bind = Super, Q, killactive,
bind = Super, F, togglefloating,
bind = Super, Return, exec, foot
bind = Super, Slash, exec, ags -t 'cheatsheet'
bind = Super, A, exec, ags -t 'overview'
bind = Super, M, exec, ags run-js 'openMusicControls.value = (!Mpris.getPlayer() ? false : !openMusicControls.value);'
bind = Super, Comma, exec, ags run-js 'openColorScheme.value = true; Utils.timeout(2000, () => openColorScheme.value = false);'
bind = Super, K, exec, ags -t 'osk'
bind = ControlAlt, Delete, exec, ags -t 'session'
bind = Super, E, exec, nautilus --new-window
bind = Super, I, exec, XDG_CURRENT_DESKTOP="gnome" gnome-control-center
bind = ControlSuper, V, exec, pavucontrol
bind = ControlShift, Escape, exec, gnome-system-monitor
bind = Super, B, exec, google-chrome-stable
bind = Super, C, exec, code
bind = Super, D, exec, discord

bind = Super, L, exec, gtklock

# Move focus with mainMod + arrow keys
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

# Audio controls
bindl = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && ags run-js 'indicator.popup(1);'
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && ags run-js 'indicator.popup(1);'
bindle=, XF86MonBrightnessUp, exec, ags run-js 'brightness.screen_value += 0.05;' && ags run-js 'indicator.popup(1);'
bindle=, XF86MonBrightnessDown, exec, ags run-js 'brightness.screen_value -= 0.05;' && ags run-js 'indicator.popup(1);'
bind = , XF86AudioPlay, exec, playerctl play-pause
bindl= ,XF86AudioNext, exec, playerctl next || playerctl position $(bc <<<"100 * $(playerctl metadata mpris:length) / 1000000 / 100")
bindl= ,XF86AudioPrev, exec, playerctl previous

# Switch workspaces with mainMod + [0-9]
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = Super SHIFT, 1, movetoworkspacesilent, 1
bind = Super SHIFT, 2, movetoworkspacesilent, 2
bind = Super SHIFT, 3, movetoworkspacesilent, 3
bind = Super SHIFT, 4, movetoworkspacesilent, 4
bind = Super SHIFT, 5, movetoworkspacesilent, 5
bind = Super SHIFT, 6, movetoworkspacesilent, 6
bind = Super SHIFT, 7, movetoworkspacesilent, 7
bind = Super SHIFT, 8, movetoworkspacesilent, 8
bind = Super SHIFT, 9, movetoworkspacesilent, 9
bind = Super SHIFT, 0, movetoworkspacesilent, 10

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

###################################### AGS keybinds #####################################
# TODO: reload ags on hyprland reload, check other servitor programs as well
