$modkey = Super

bind = $modkey, Q, killactive,
bind = $modkey, F, togglefloating,
bind = $modkey, Return, exec, foot
bind = $modkey, Slash, exec, ags -t 'cheatsheet'
bind = $modkey, A, exec, ags -t 'overview'
bind = $modkey, M, exec, ags run-js 'openMusicControls.value = (!Mpris.getPlayer() ? false : !openMusicControls.value);'
bind = $modkey, Comma, exec, ags run-js 'openColorScheme.value = true; Utils.timeout(2000, () => openColorScheme.value = false);'
bind = $modkey, P, exec, ags -t 'session_menu'
bind = $modkey, E, exec, nautilus --new-window
bind = $modkey, I, exec, XDG_CURRENT_DESKTOP="gnome" gnome-control-center
bind = $modkey, B, exec, google-chrome-stable
bind = $modkey, C, exec, code
bind = $modkey, D, exec, discord

# Move focus with mainMod + arrow keys
bind = $modkey, left, movefocus, l
bind = $modkey, right, movefocus, r
bind = $modkey, up, movefocus, u
bind = $modkey, down, movefocus, d

# Audio controls
bindl = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && ags run-js 'indicator.popup(1);'
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && ags run-js 'indicator.popup(1);'
bindle=, XF86MonBrightnessUp, exec, ags run-js 'brightness.screen_value += 0.05;' && ags run-js 'indicator.popup(1);'
bindle=, XF86MonBrightnessDown, exec, ags run-js 'brightness.screen_value -= 0.05;' && ags run-js 'indicator.popup(1);'
bind = , XF86AudioPlay, exec, playerctl play-pause
bindl= ,XF86AudioNext, exec, playerctl next
bindl= ,XF86AudioPrev, exec, playerctl previous

# Switch workspaces with mainMod + [0-9]
bind = $modkey, 1, workspace, 1
bind = $modkey, 2, workspace, 2
bind = $modkey, 3, workspace, 3
bind = $modkey, 4, workspace, 4
bind = $modkey, 5, workspace, 5
bind = $modkey, 6, workspace, 6
bind = $modkey, 7, workspace, 7
bind = $modkey, 8, workspace, 8
bind = $modkey, 9, workspace, 9
bind = $modkey, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $modkey SHIFT, 1, movetoworkspacesilent, 1
bind = $modkey SHIFT, 2, movetoworkspacesilent, 2
bind = $modkey SHIFT, 3, movetoworkspacesilent, 3
bind = $modkey SHIFT, 4, movetoworkspacesilent, 4
bind = $modkey SHIFT, 5, movetoworkspacesilent, 5
bind = $modkey SHIFT, 6, movetoworkspacesilent, 6
bind = $modkey SHIFT, 7, movetoworkspacesilent, 7
bind = $modkey SHIFT, 8, movetoworkspacesilent, 8
bind = $modkey SHIFT, 9, movetoworkspacesilent, 9
bind = $modkey SHIFT, 0, movetoworkspacesilent, 10

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $modkey, mouse:272, movewindow
bindm = $modkey, mouse:273, resizewindow
