#!/bin/bash

project_root=$(dirname $0)/../

source $project_root/installer/util.sh

function quit {
  echo "Exiting..."
  exit 0
}

function confirm_quit {
  echo "SIGINT received, press CTRL+C again to quit"

  trap "quit" SIGINT
}

function install_config {
  # Install stow and git
  packages=("stow" "git")

  inform_user "Installing stow and git to manage dotfiles in the home directory"
  sudo apt install "${packages[@]}"

  # Copy dotfiles for current user using gnu stow
  inform_user "Copying dotfiles to home directory"

  # Create required directories independent from the symlink farm
  mkdir -p ~/.local/{bin,share,lib} ~/.config

  # Create the symlink farm (copy dotfiles to the home directory using stow)
  stow . -d $project_root -t ~
}

function main {
  # Check if the script is run as root, this is bad
  if [[ "$(whoami)" == "root" ]]; then
    echo "Please run this script as a normal user"
    exit 1
  fi

  trap "confirm_quit" SIGINT

  echo "WSL Dotfiles Installer"
  echo "Running as $(whoami)"
  cd $project_root

  # Update
  inform_user "Updating system to ensure no broken package dependencies"
  sudo apt update && sudo apt upgrade

  # Install stow and git
  confirm_installation "Do you want to install personal configurations?" install_config

  # Install all relevant features
  inform_user "Installing all features"

  # Install modules
  for module in ./installer/*/module.sh; do
    source $module
    confirm_installation "Do you want to install $(basename $(dirname $module))?" module
  done
}

main
