#!/bin/bash

source ~/.dotfiles/installer/util.sh

function quit {
  echo "Exiting..."
  exit 0
}

function confirm_quit {
  echo "SIGINT received, press CTRL+C again to quit"

  trap "quit" SIGINT
}

trap "confirm_quit" SIGINT

# Check if the script is run as root, this is bad
if [[ "$(whoami)" == "root" ]]; then
  echo "Please run this script as a normal user"
  exit 1
fi

echo "WSL Dotfiles Installer"
echo "Running as $(whoami)"
cd # Go to home directory

# Update
inform_user "Updating system to ensure no broken package dependencies"
sudo apt update && sudo apt upgrade

# Install stow and git
packages=("stow" "git")

inform_user "Installing stow and git to manage dotfiles in the home directory"
sudo apt install "${packages[@]}"

# Install all relevant features
for entry in "$(find ~/.dotfiles/installer -type d)"; do
  if [[ -f ./$entry/module.sh ]]; then
    inform_user "Installing $(basename $entry)"
    source ./$entry/module.sh
    module-$(basename $entry)
  fi
done

# Copy dotfiles for current user using gnu stow
inform_user "Copying dotfiles to home directory"
cd ~/.dotfiles
stow .
